title: "Photographer Portfolio"
description: "Photography Portfolio"
baseurl: "/holy_father_port" # Назва репозиторію для GitHub Pages
url: "https://smithe941.github.io" # GitHub Pages URL

# GitHub Pages налаштування
plugins:
  - jekyll-sass-converter

sass:
  style: compressed
  sourcemap: never

# Виключення файлів з обробки
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - .gitignore
  - .git
  - .github

# Включення директорій
include:
  - assets

